name: "FLAIR — LLM Code Review"
description: "Use an LLM to review PR diffs and post comments via GitHub Actions."
author: "Your Name"

inputs:
  llm-endpoint:
    description: "LLM server URL (e.g. http://localhost:8080/predict)"
    required: true
  diff-chunk-size:
    description: "Max diff chunk size (chars)"
    required: false
    default: "10000"
  exclude-patterns:
    description: "Comma-separated file patterns to skip (e.g. test,spec)"
    required: false
    default: "test,tests,spec"
  github-token:
    description: "GitHub token with repo/comments write access"
    required: true
  summary-mode:
    description: "true to post one PR Review with summary+inline, false for per-comment"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.8"

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r "${{ github.action_path }}/requirements.txt"

    - name: Run code review
      shell: bash
      env:
        GITHUB_TOKEN:      ${{ inputs.github-token }}
        LLM_ENDPOINT:      ${{ inputs.llm-endpoint }}
        DIFF_CHUNK_SIZE:   ${{ inputs.diff-chunk-size }}
        EXCLUDE_PATTERNS:  ${{ inputs.exclude-patterns }}
        SUMMARY_MODE:      ${{ inputs.summary-mode }}
        REPOSITORY_GITHUB: ${{ github.repository }}
        PR_NUMBER_GITHUB:  ${{ github.event.pull_request.number }}
        GITHUB_API_URL:    https://api.github.com
      run: |
        python "${{ github.action_path }}/src/action.py"