name: "LLM Code Review Action"
description: "An automated code review action that uses an LLM (e.g., Qwen2.5-coder) to analyze diffs and post review comments on pull requests."
author: "jo15122002"
inputs:
  llm-endpoint:
    description: "Endpoint URL of the LLM server (e.g., https://your-llm.example.com/completion)"
    required: true
  diff-chunk-size:
    description: "Maximum size (in characters or max lines) for diff chunks"
    required: false
    default: "10000"
  exclude-patterns:
    description: "Comma-separated list of file patterns to exclude (e.g., test,tests,spec)"
    required: false
    default: "test,tests,spec"
runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run LLM Code Review
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        LLM_ENDPOINT: ${{ inputs.llm-endpoint }}
        DIFF_CHUNK_SIZE: ${{ inputs.diff-chunk-size }}
        EXCLUDE_PATTERNS: ${{ inputs.exclude-patterns }}
        CI_PLATFORM: github
      run: |
        python src/main.py
