import logging
from config import load_config
from diff import fetch_pr_diff, filter_diff, split_diff
from llm import call_llm, extract_comments
from publish import post_review, post_per_comment

def main():
    cfg = load_config()
    logging.basicConfig(level=logging.INFO)

    # 1) Récupérer le diff complet de la PR
    full_diff = fetch_pr_diff(cfg.REPOSITORY_GITHUB, cfg.PR_NUMBER_GITHUB, cfg.GITHUB_TOKEN)
    if not full_diff:
        logging.error("No diff fetched; aborting.")
        return

    # 2) Filtrer puis découper pour alimenter l’LLM
    filtered = filter_diff(full_diff, cfg.EXCLUDE_PATTERNS)
    chunks   = split_diff(filtered, cfg.DIFF_CHUNK_SIZE)
    logging.info("Diff split into %d chunk(s).", len(chunks))

    # 3) Interroger l’LLM chunk par chunk
    all_comments = []
    for idx, chunk in enumerate(chunks, start=1):
        logging.info("Chunk %d/%d", idx, len(chunks))
        reply   = call_llm(chunk, cfg)
        comments = extract_comments(reply)
        for c in comments:
            c["_chunk"]     = chunk         # Pour le prompt / debug
            c["_full_diff"] = filtered      # Pour le mapping des positions
        all_comments.extend(comments)

    if not all_comments:
        logging.info("No suggestions generated by the LLM.")
        return

    # 4) Publier selon le mode
    if cfg.SUMMARY_MODE:
        logging.info("Posting as a single PR review with inline suggestions…")
        success = post_review(all_comments, cfg)
    else:
        logging.info("Posting one issue comment per suggestion…")
        success = post_per_comment(all_comments, cfg)

    if success:
        logging.info("✔️  Publishing completed successfully.")
    else:
        logging.error("❌  Publishing failed.")

if __name__ == "__main__":
    main()