name: "Cleanup PR Comments"

on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: "Pull request number to clean up"
        required: true
        default: ""

jobs:
  delete-pr-comments:
    name: "Delete All PR Comments"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install Dependencies
        run: pip install requests

      - name: Delete PR Comments
        env:
          REPOSITORY_GITHUB: ${{ github.repository }}
          # Use the input if provided, else fallback to pull_request number
          PR_NUMBER_GITHUB: ${{ github.event.inputs.pr_number != '' && github.event.inputs.pr_number || github.event.pull_request.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python src/delete_pr_comments.py

  delete-workflow-comments:
    name: "Delete Workflow Comments"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install Dependencies
        run: pip install requests

      - name: Delete Workflow Comments
        env:
          REPOSITORY_GITHUB: ${{ github.repository }}
          PR_NUMBER_GITHUB: ${{ github.event.inputs.pr_number != '' && github.event.inputs.pr_number || github.event.pull_request.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python src/delete_workflow_comments.py
